DISPLAY_X = 1200
DISPLAY_Y = 900
FPS = 60

RDM = int(DISPLAY_X / 8)   # relative horizontal distance measure unit
FIGHTER_SIZE = (int(DISPLAY_X // 8), int(DISPLAY_Y // 3))
DUCKING_FIGHTER_SIZE = (int(DISPLAY_X // 8), int(DISPLAY_Y // 4))
MOVE_SPEED = DISPLAY_X // 240
FLOOR = DISPLAY_Y - DISPLAY_Y // 3.6

FULL_HP = 100
states = {"idle", "main_menu", "victory", "defeat", "gameplay"}

TEXT_BG_COLOR = "YELLOW"
BG_COLOR = (102, 205, 170)
TEXT_COLOR = "RED"

DASH_DURATION = 13
DASH_COOlDOWN = 4
DASH_MULTIPLIER = 2.5
DOUBLE_TAP_DURATION = 14

JAB_DURATION = 14
STAGGER_DURATION = 14
MIN_DUCKING_DURATION = 20

HAND_COLLISION_SIZE = (DISPLAY_X / 17, DISPLAY_Y / 23)

PLAYER_STARTING_POS = (DISPLAY_X // 4.5, FLOOR)
ENEMY_STARTING_POS = (DISPLAY_X - DISPLAY_X // 4.5 - FIGHTER_SIZE[0], FLOOR)
